name: Java CI + SonarCloud
on:
  push:
  pull_request:

jobs:
  quality:
    runs-on: ubuntu-latest
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: 'maven'

      - name: Verify & Sonar analysis
        shell: bash
        run: |
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.projectKey="$(echo ${{ github.repository }} | sed 's-/-_-')" \
            -Dsonar.organization="CERI-M1-DevOps" \
            -Dsonar.host.url="https://sonarcloud.io" \
            -Dsonar.qualitygate.wait=true \
            -Dsonar.login=$SONAR_TOKEN