name: Java CI with Maven - Test and package
on : [push]

jobs:
  build:
    runs-on: ubuntu-latest

  steps:
    - name: Setup Checkout
      uses: actions/checkout@v4

    - name: SetUp java JDK 17
      uses: actions/setup-java@v4

    - name : build with maven
      uses :  mvn –B package